/**
 * COUNTER JOURNAL DESIGN NOTE: The about page uses broad editorial pacing and
 * honest neighborhood language rather than a generic company profile.
 */
import { HeartHandshake, Leaf, UsersRound } from "lucide-react";
import { assets } from "@/data/cafeData";

const values = [{ icon: HeartHandshake, title: "Make room for the regulars", text: "We remember a favorite order, make space at the counter, and keep the welcome unhurried." }, { icon: Leaf, title: "Buy with intention", text: "We choose thoughtful ingredients, make what we can in small batches, and keep waste in view." }, { icon: UsersRound, title: "Belong to the block", text: "This is a café first, but it is also a place to run into a neighbor and stay a little longer." }];
export default function About() { return <>
  <section className="px-4 py-14 sm:px-6 lg:px-8"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[.9fr_1.1fr]"><div><p className="section-kicker">Our story</p><h1 className="mt-4 font-display text-6xl leading-[.94]">A counter made for<br /><em className="font-normal text-[#c97b3d]">the in-between.</em></h1><p className="mt-7 max-w-md text-base leading-8 text-[#645447]">The Daily Grind started with a simple idea: your everyday coffee can still feel considered. No grand ceremony, just good ingredients, good rhythm, and the reliable comfort of a local place.</p></div><div className="relative"><img src={assets.hero} className="h-[420px] w-full object-cover shadow-[16px_16px_0_#e9e0d4]" alt="The Daily Grind’s sunlit coffee bar" /><div className="absolute -bottom-6 -left-2 max-w-[235px] bg-[#3a2a1e] p-5 text-[#faf6f1] sm:-left-6"><p className="text-xs font-bold uppercase tracking-[0.14em] text-[#eacba2]">Our promise</p><p className="mt-2 font-display text-2xl">Come as you are. Leave a little better caffeinated.</p></div></div></div></section>
  <section className="mt-8 bg-[#e9e0d4] px-4 py-20 sm:px-6 lg:px-8"><div className="mx-auto max-w-4xl"><p className="section-kicker">Why we’re here</p><p className="mt-4 font-display text-4xl leading-tight">“A daily ritual is more than a drink. It’s how a neighborhood keeps time.”</p><div className="mt-10 space-y-6 text-base leading-8 text-[#645447]"><p>We believe a café should work as well for the two-minute pickup as it does for the long conversation that follows. That means bright coffee, warm baking, clear prices, and service that never asks you to perform a version of yourself.</p><p>Our small team brings the same care to the first cappuccino of the morning as the last cold brew of the afternoon. We call that our daily grind, and we’re glad to share it.</p></div></div></section>
  <section className="px-4 py-20 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl"><p className="section-kicker">How we work</p><div className="mt-7 grid gap-5 md:grid-cols-3">{values.map(({ icon: Icon, title, text }) => <article key={title} className="border-t-4 border-double border-[#3a2a1e] bg-white p-7 shadow-[0_12px_30px_rgba(58,42,30,0.06)]"><Icon className="text-[#c97b3d]" size={28} /><h2 className="mt-6 font-display text-3xl">{title}</h2><p className="mt-3 text-sm leading-6 text-[#645447]">{text}</p></article>)}</div></div></section>
  </>; }
