/**
 * COUNTER JOURNAL DESIGN NOTE: Contact balances a written note card against
 * clear practical details, with a deliberately non-network map placeholder.
 */
import { useState } from "react";
import { Clock3, Mail, MapPin, Phone } from "lucide-react";
import { cafe } from "@/data/cafeData";

export default function Contact() {
  const [submitted, setSubmitted] = useState(false);
  return <section className="px-4 py-14 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl"><div className="border-b-4 border-double border-[#3a2a1e] pb-10"><p className="section-kicker">Find the counter</p><h1 className="mt-4 font-display text-6xl leading-none">Leave a note.<br /><em className="font-normal text-[#c97b3d]">Come say hello.</em></h1></div><div className="mt-12 grid gap-10 lg:grid-cols-[1.05fr_.95fr]"><div className="bg-white p-6 shadow-[0_14px_40px_rgba(58,42,30,0.08)] sm:p-8">{submitted ? <div className="grid min-h-80 place-items-center text-center"><div><p className="section-kicker text-[#6b8f71]">Note received</p><h2 className="mt-4 font-display text-4xl">We’ll be in touch soon.</h2><p className="mx-auto mt-4 max-w-sm text-sm leading-6 text-[#645447]">Thanks for reaching out to the team. Your message is stored only in this browser prototype.</p><button onClick={() => setSubmitted(false)} className="mt-6 text-xs font-bold uppercase tracking-[0.14em] text-[#c97b3d] underline underline-offset-4">Send another note</button></div></div> : <form onSubmit={(event) => { event.preventDefault(); setSubmitted(true); }}><p className="section-kicker">Write to us</p><div className="mt-7 grid gap-5"><label className="field-label">Name<input required className="field-control mt-2" name="name" autoComplete="name" /></label><label className="field-label">Email<input required type="email" className="field-control mt-2" name="email" autoComplete="email" /></label><label className="field-label">Message<textarea required className="field-control mt-2 min-h-32 resize-y" name="message" /></label><button className="mt-2 bg-[#3a2a1e] px-5 py-4 text-xs font-bold uppercase tracking-[0.14em] text-[#faf6f1] transition hover:bg-[#c97b3d]">Send the note</button></div></form>}</div><aside><div className="grid h-56 place-items-center border border-dashed border-[#3a2a1e]/30 bg-[#e9e0d4] p-6 text-center"><MapPin size={28} className="text-[#c97b3d]" /><p className="mt-3 font-display text-2xl">123 Main St</p><p className="mt-1 text-xs uppercase tracking-[0.14em] text-[#645447]">Map available in person · Offline prototype</p></div><div className="mt-7 grid gap-5 text-sm"><div className="flex gap-3"><Phone className="shrink-0 text-[#c97b3d]" size={19} /><div><p className="font-bold">Call ahead</p><p className="mt-1 text-[#645447]">{cafe.phone}</p></div></div><div className="flex gap-3"><Mail className="shrink-0 text-[#c97b3d]" size={19} /><div><p className="font-bold">Write anytime</p><p className="mt-1 text-[#645447]">{cafe.email}</p></div></div><div className="flex gap-3"><Clock3 className="shrink-0 text-[#c97b3d]" size={19} /><div><p className="font-bold">Hours</p>{Object.entries(cafe.hours).map(([day, hours]) => <p key={day} className="mt-1 text-[#645447]"><strong>{day}</strong> · {hours}</p>)}</div></div></div></aside></div></div></section>;
}

