/**
 * COUNTER JOURNAL DESIGN NOTE: Home is an editorial first impression where a
 * modest counter story, warm imagery, and clear ordering entry points lead.
 */
import { ArrowRight, Clock3, MapPin, Phone } from "lucide-react";
import { Link } from "wouter";
import { MenuCard } from "@/components/MenuCard";
import { cafe, assets, featuredItems } from "@/data/cafeData";

export default function Home() {
  return <>
    <section className="relative isolate overflow-hidden border-b border-[#3a2a1e]/15 bg-[#3a2a1e] px-4 py-10 text-[#faf6f1] sm:px-6 lg:px-8 lg:py-16"><img src={assets.hero} alt="Warm espresso counter at The Daily Grind" className="absolute inset-0 h-full w-full object-cover opacity-60" /><div className="absolute inset-0 bg-gradient-to-r from-[#3a2a1e]/90 via-[#3a2a1e]/68 to-[#3a2a1e]/25" /><div className="relative mx-auto grid min-h-[520px] max-w-7xl items-end gap-8 lg:grid-cols-[1.1fr_.9fr]">
      <div className="max-w-2xl pb-2"><p className="section-kicker text-[#eacba2]">Est. 2026 · 123 Main St</p><h1 className="mt-4 font-display text-5xl leading-[0.92] sm:text-6xl lg:text-8xl">Your morning,<br /><em className="font-normal text-[#eacba2]">poured</em> with intention.</h1><p className="mt-6 max-w-md text-base leading-7 text-[#faf6f1]/85">{cafe.tagline}. Pull up a stool for the usual, or try something that makes the routine feel new.</p><Link href="/menu" className="mt-8 inline-flex items-center gap-3 bg-[#c97b3d] px-6 py-4 text-xs font-bold uppercase tracking-[0.15em] text-white transition hover:-translate-y-1 hover:bg-[#faf6f1] hover:text-[#3a2a1e]">View the menu <ArrowRight size={17} /></Link></div>
      <aside className="mb-1 border border-[#faf6f1]/35 bg-[#faf6f1]/95 p-6 text-[#3a2a1e] shadow-xl backdrop-blur-sm lg:ml-auto lg:max-w-sm"><div className="flex items-center justify-between border-b border-[#3a2a1e]/15 pb-4"><p className="section-kicker">Today at the counter</p><img src={assets.glyph} className="h-8 w-8 object-contain" alt="" /></div><p className="mt-5 font-display text-3xl leading-tight">A good cup is a small act of care.</p><p className="mt-3 text-sm leading-6 text-[#645447]">Small-batch espresso, a daily pastry case, and plenty of room to pause before the day gets loud.</p><Link href="/about" className="mt-5 inline-block text-xs font-bold uppercase tracking-[0.14em] text-[#c97b3d] underline underline-offset-4">Our story</Link></aside>
    </div></section>
    <section className="border-b border-[#3a2a1e]/15 bg-[#e9e0d4] px-4 py-5 sm:px-6 lg:px-8"><div className="mx-auto grid max-w-7xl gap-4 text-sm sm:grid-cols-3"><div className="flex items-center gap-3"><Clock3 className="text-[#c97b3d]" size={19} /><span><strong>Weekdays</strong> · {cafe.hours["Monday–Friday"]}</span></div><div className="flex items-center gap-3"><MapPin className="text-[#c97b3d]" size={19} /><span><strong>Find us</strong> · {cafe.location}</span></div><div className="flex items-center gap-3"><Phone className="text-[#c97b3d]" size={19} /><span><strong>Call ahead</strong> · {cafe.phone}</span></div></div></section>
    <section className="px-4 py-20 sm:px-6 lg:px-8"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[.9fr_1.1fr]"><div className="lg:pr-10"><p className="section-kicker">The neighborhood cup</p><h2 className="mt-4 font-display text-5xl leading-[.98]">Start slow.<br />Take it with you.</h2><p className="mt-6 max-w-md text-base leading-8 text-[#645447]">We built The Daily Grind around the kind of coffee stop you remember: a friendly face, a pastry still warm from the oven, and a cup that travels well into the rest of the day.</p><Link href="/about" className="mt-8 inline-flex items-center gap-2 border-b border-[#3a2a1e] pb-1 text-xs font-bold uppercase tracking-[0.14em]">Meet the café <ArrowRight size={16} /></Link></div><div className="relative"><div className="absolute -left-6 -top-6 hidden h-28 w-28 border border-[#c97b3d]/50 lg:block" /><img src={assets.breakfast} className="relative h-[390px] w-full object-cover shadow-[16px_16px_0_#e9e0d4]" alt="Avocado toast and cold brew on a café table" /></div></div></section>
    <section className="border-y border-[#3a2a1e]/12 bg-white px-4 py-20 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl"><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="section-kicker">From the daily case</p><h2 className="mt-3 font-display text-5xl">Counter favorites.</h2></div><Link href="/menu" className="text-xs font-bold uppercase tracking-[0.14em] text-[#c97b3d] underline underline-offset-4">See all menu items</Link></div><div className="mt-10 grid gap-6 sm:grid-cols-2 xl:grid-cols-4">{featuredItems.map((item) => <MenuCard key={item.id} item={item} />)}</div></div></section>
  </>;
}
