/**
 * COUNTER JOURNAL DESIGN NOTE: Test console is an honest working bench for
 * support QA—clear tags, annotated results, and portable offline records.
 */
import { useMemo, useState } from "react";
import { Download, MessageSquareText } from "lucide-react";
import { answerQuestion, testQuestions } from "@/utils/chatbot";

type Status = "Correct" | "Vague" | "Wrong";
type Row = { question: string; answer: string; intent: string; status: Status; note: string };
const initialRows = testQuestions.map((question) => { const reply = answerQuestion(question); return { question, answer: reply.text, intent: reply.intent, status: reply.intent === "fallback" ? "Vague" as Status : "Correct" as Status, note: "" }; });
const statusClass: Record<Status, string> = { Correct: "bg-[#e1eee1] text-[#45694b]", Vague: "bg-[#f7e9cc] text-[#8a5a1f]", Wrong: "bg-[#f6dfda] text-[#9d3f2e]" };

export default function TestConsole() {
  const [rows, setRows] = useState<Row[]>(initialRows);
  const exportLog = () => { const header = "question,answer,intent,status,note"; const csv = [header, ...rows.map((row) => [row.question, row.answer, row.intent, row.status, row.note].map((entry) => `"${entry.replaceAll('"', '""')}"`).join(","))].join("\n"); const url = URL.createObjectURL(new Blob([csv], { type: "text/csv" })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = "daily-grind-chat-test-log.csv"; anchor.click(); URL.revokeObjectURL(url); };
  const score = useMemo(() => rows.filter((row) => row.status === "Correct").length, [rows]);
  return <section className="px-4 py-12 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl"><div className="flex flex-wrap items-end justify-between gap-6 border-b-4 border-double border-[#3a2a1e] pb-8"><div><p className="section-kicker">Internal working bench</p><h1 className="mt-3 font-display text-5xl">FAQ test console</h1><p className="mt-3 max-w-xl text-sm leading-6 text-[#645447]">Offline transcript review for the rule-based counter assistant. Tag each exchange after manual QA.</p></div><button onClick={exportLog} className="inline-flex items-center gap-2 bg-[#c97b3d] px-5 py-3 text-xs font-bold uppercase tracking-[0.13em] text-white hover:bg-[#3a2a1e]"><Download size={16} /> Export log</button></div><div className="mt-8 grid gap-5 md:grid-cols-[.42fr_1fr]"><aside className="border-t-4 border-double border-[#3a2a1e] bg-[#e9e0d4] p-6"><div className="ticket-meta -mx-6 -mt-6 mb-6"><span><i className="ticket-dot" /> QA logbook</span><span>v1.0</span></div><MessageSquareText className="text-[#c97b3d]" size={30} /><p className="mt-5 text-xs font-bold uppercase tracking-[0.14em] text-[#645447]">Manual review progress</p><p className="mt-2 font-display text-5xl">{score}<span className="text-2xl"> / {rows.length}</span></p><p className="mt-4 text-sm leading-6 text-[#645447]">Fallback responses are marked “Vague” initially because they correctly withhold unknown information. Review any specific requirement with staff.</p></aside><div className="space-y-4">{rows.map((row, index) => <article key={row.question} className="ticket-row bg-white p-5 shadow-[0_10px_25px_rgba(58,42,30,0.06)]"><div className="flex flex-wrap items-start justify-between gap-3"><p className="font-semibold">{index + 1}. {row.question}</p><select aria-label={`Status for question ${index + 1}`} value={row.status} onChange={(event) => setRows((current) => current.map((item, itemIndex) => itemIndex === index ? { ...item, status: event.target.value as Status } : item))} className={`px-2 py-1 text-xs font-bold ${statusClass[row.status]}`}><option value="Correct">✅ Correct</option><option value="Vague">⚠️ Vague</option><option value="Wrong">❌ Wrong</option></select></div><p className="mt-3 border-l-2 border-[#c97b3d] pl-3 text-sm leading-6 text-[#645447]">{row.answer}</p><p className="mt-3 text-[10px] font-bold uppercase tracking-[0.13em] text-[#6b8f71]">Intent: {row.intent}</p><label className="mt-3 block text-xs font-bold uppercase tracking-[0.12em] text-[#645447]">Review note<input value={row.note} onChange={(event) => setRows((current) => current.map((item, itemIndex) => itemIndex === index ? { ...item, note: event.target.value } : item))} className="field-control mt-1 text-sm font-normal normal-case tracking-normal" placeholder="Add a reviewer note" /></label></article>)}</div></div></div></section>;
}
